// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockApplicationRepository is an autogenerated mock type for the ApplicationRepository type
type MockApplicationRepository struct {
	mock.Mock
}

type MockApplicationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationRepository) EXPECT() *MockApplicationRepository_Expecter {
	return &MockApplicationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, app
func (_m *MockApplicationRepository) Create(ctx context.Context, app *domain.Application) (*domain.Application, error) {
	ret := _m.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Application) (*domain.Application, error)); ok {
		return rf(ctx, app)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Application) *domain.Application); ok {
		r0 = rf(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Application) error); ok {
		r1 = rf(ctx, app)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplicationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockApplicationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - app *domain.Application
func (_e *MockApplicationRepository_Expecter) Create(ctx interface{}, app interface{}) *MockApplicationRepository_Create_Call {
	return &MockApplicationRepository_Create_Call{Call: _e.mock.On("Create", ctx, app)}
}

func (_c *MockApplicationRepository_Create_Call) Run(run func(ctx context.Context, app *domain.Application)) *MockApplicationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Application))
	})
	return _c
}

func (_c *MockApplicationRepository_Create_Call) Return(_a0 *domain.Application, _a1 error) *MockApplicationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplicationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Application) (*domain.Application, error)) *MockApplicationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEnvVar provides a mock function with given fields: ctx, env
func (_m *MockApplicationRepository) CreateEnvVar(ctx context.Context, env *domain.EnvironmentVariable) error {
	ret := _m.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvVar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EnvironmentVariable) error); ok {
		r0 = rf(ctx, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_CreateEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEnvVar'
type MockApplicationRepository_CreateEnvVar_Call struct {
	*mock.Call
}

// CreateEnvVar is a helper method to define mock.On call
//   - ctx context.Context
//   - env *domain.EnvironmentVariable
func (_e *MockApplicationRepository_Expecter) CreateEnvVar(ctx interface{}, env interface{}) *MockApplicationRepository_CreateEnvVar_Call {
	return &MockApplicationRepository_CreateEnvVar_Call{Call: _e.mock.On("CreateEnvVar", ctx, env)}
}

func (_c *MockApplicationRepository_CreateEnvVar_Call) Run(run func(ctx context.Context, env *domain.EnvironmentVariable)) *MockApplicationRepository_CreateEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.EnvironmentVariable))
	})
	return _c
}

func (_c *MockApplicationRepository_CreateEnvVar_Call) Return(_a0 error) *MockApplicationRepository_CreateEnvVar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_CreateEnvVar_Call) RunAndReturn(run func(context.Context, *domain.EnvironmentVariable) error) *MockApplicationRepository_CreateEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, appID
func (_m *MockApplicationRepository) Delete(ctx context.Context, appID int64) error {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockApplicationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockApplicationRepository_Expecter) Delete(ctx interface{}, appID interface{}) *MockApplicationRepository_Delete_Call {
	return &MockApplicationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, appID)}
}

func (_c *MockApplicationRepository_Delete_Call) Run(run func(ctx context.Context, appID int64)) *MockApplicationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApplicationRepository_Delete_Call) Return(_a0 error) *MockApplicationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockApplicationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEnvVar provides a mock function with given fields: ctx, appID, key
func (_m *MockApplicationRepository) DeleteEnvVar(ctx context.Context, appID int64, key string) error {
	ret := _m.Called(ctx, appID, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEnvVar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, appID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_DeleteEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEnvVar'
type MockApplicationRepository_DeleteEnvVar_Call struct {
	*mock.Call
}

// DeleteEnvVar is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
//   - key string
func (_e *MockApplicationRepository_Expecter) DeleteEnvVar(ctx interface{}, appID interface{}, key interface{}) *MockApplicationRepository_DeleteEnvVar_Call {
	return &MockApplicationRepository_DeleteEnvVar_Call{Call: _e.mock.On("DeleteEnvVar", ctx, appID, key)}
}

func (_c *MockApplicationRepository_DeleteEnvVar_Call) Run(run func(ctx context.Context, appID int64, key string)) *MockApplicationRepository_DeleteEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockApplicationRepository_DeleteEnvVar_Call) Return(_a0 error) *MockApplicationRepository_DeleteEnvVar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_DeleteEnvVar_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockApplicationRepository_DeleteEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, appID
func (_m *MockApplicationRepository) GetByID(ctx context.Context, appID int64) (*domain.Application, error) {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Application, error)); ok {
		return rf(ctx, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Application); ok {
		r0 = rf(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplicationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockApplicationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockApplicationRepository_Expecter) GetByID(ctx interface{}, appID interface{}) *MockApplicationRepository_GetByID_Call {
	return &MockApplicationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, appID)}
}

func (_c *MockApplicationRepository_GetByID_Call) Run(run func(ctx context.Context, appID int64)) *MockApplicationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApplicationRepository_GetByID_Call) Return(_a0 *domain.Application, _a1 error) *MockApplicationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplicationRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Application, error)) *MockApplicationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockApplicationRepository) List(ctx context.Context, opts domain.ApplicationListOptions) ([]*domain.Application, int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Application
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApplicationListOptions) ([]*domain.Application, int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApplicationListOptions) []*domain.Application); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ApplicationListOptions) int64); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ApplicationListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockApplicationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockApplicationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.ApplicationListOptions
func (_e *MockApplicationRepository_Expecter) List(ctx interface{}, opts interface{}) *MockApplicationRepository_List_Call {
	return &MockApplicationRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockApplicationRepository_List_Call) Run(run func(ctx context.Context, opts domain.ApplicationListOptions)) *MockApplicationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ApplicationListOptions))
	})
	return _c
}

func (_c *MockApplicationRepository_List_Call) Return(_a0 []*domain.Application, _a1 int64, _a2 error) *MockApplicationRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockApplicationRepository_List_Call) RunAndReturn(run func(context.Context, domain.ApplicationListOptions) ([]*domain.Application, int64, error)) *MockApplicationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListEnvVars provides a mock function with given fields: ctx, appID
func (_m *MockApplicationRepository) ListEnvVars(ctx context.Context, appID int64) ([]domain.EnvironmentVariable, error) {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvVars")
	}

	var r0 []domain.EnvironmentVariable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.EnvironmentVariable, error)); ok {
		return rf(ctx, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.EnvironmentVariable); ok {
		r0 = rf(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.EnvironmentVariable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplicationRepository_ListEnvVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnvVars'
type MockApplicationRepository_ListEnvVars_Call struct {
	*mock.Call
}

// ListEnvVars is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockApplicationRepository_Expecter) ListEnvVars(ctx interface{}, appID interface{}) *MockApplicationRepository_ListEnvVars_Call {
	return &MockApplicationRepository_ListEnvVars_Call{Call: _e.mock.On("ListEnvVars", ctx, appID)}
}

func (_c *MockApplicationRepository_ListEnvVars_Call) Run(run func(ctx context.Context, appID int64)) *MockApplicationRepository_ListEnvVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApplicationRepository_ListEnvVars_Call) Return(_a0 []domain.EnvironmentVariable, _a1 error) *MockApplicationRepository_ListEnvVars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplicationRepository_ListEnvVars_Call) RunAndReturn(run func(context.Context, int64) ([]domain.EnvironmentVariable, error)) *MockApplicationRepository_ListEnvVars_Call {
	_c.Call.Return(run)
	return _c
}

// SyncEnvVars provides a mock function with given fields: ctx, appID, envVars
func (_m *MockApplicationRepository) SyncEnvVars(ctx context.Context, appID int64, envVars []domain.EnvironmentVariable) error {
	ret := _m.Called(ctx, appID, envVars)

	if len(ret) == 0 {
		panic("no return value specified for SyncEnvVars")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []domain.EnvironmentVariable) error); ok {
		r0 = rf(ctx, appID, envVars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_SyncEnvVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncEnvVars'
type MockApplicationRepository_SyncEnvVars_Call struct {
	*mock.Call
}

// SyncEnvVars is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
//   - envVars []domain.EnvironmentVariable
func (_e *MockApplicationRepository_Expecter) SyncEnvVars(ctx interface{}, appID interface{}, envVars interface{}) *MockApplicationRepository_SyncEnvVars_Call {
	return &MockApplicationRepository_SyncEnvVars_Call{Call: _e.mock.On("SyncEnvVars", ctx, appID, envVars)}
}

func (_c *MockApplicationRepository_SyncEnvVars_Call) Run(run func(ctx context.Context, appID int64, envVars []domain.EnvironmentVariable)) *MockApplicationRepository_SyncEnvVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]domain.EnvironmentVariable))
	})
	return _c
}

func (_c *MockApplicationRepository_SyncEnvVars_Call) Return(_a0 error) *MockApplicationRepository_SyncEnvVars_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_SyncEnvVars_Call) RunAndReturn(run func(context.Context, int64, []domain.EnvironmentVariable) error) *MockApplicationRepository_SyncEnvVars_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, app, appID
func (_m *MockApplicationRepository) Update(ctx context.Context, app *domain.Application, appID int64) error {
	ret := _m.Called(ctx, app, appID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Application, int64) error); ok {
		r0 = rf(ctx, app, appID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockApplicationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - app *domain.Application
//   - appID int64
func (_e *MockApplicationRepository_Expecter) Update(ctx interface{}, app interface{}, appID interface{}) *MockApplicationRepository_Update_Call {
	return &MockApplicationRepository_Update_Call{Call: _e.mock.On("Update", ctx, app, appID)}
}

func (_c *MockApplicationRepository_Update_Call) Run(run func(ctx context.Context, app *domain.Application, appID int64)) *MockApplicationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Application), args[2].(int64))
	})
	return _c
}

func (_c *MockApplicationRepository_Update_Call) Return(_a0 error) *MockApplicationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Application, int64) error) *MockApplicationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEnvVar provides a mock function with given fields: ctx, env
func (_m *MockApplicationRepository) UpdateEnvVar(ctx context.Context, env *domain.EnvironmentVariable) error {
	ret := _m.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEnvVar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EnvironmentVariable) error); ok {
		r0 = rf(ctx, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_UpdateEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEnvVar'
type MockApplicationRepository_UpdateEnvVar_Call struct {
	*mock.Call
}

// UpdateEnvVar is a helper method to define mock.On call
//   - ctx context.Context
//   - env *domain.EnvironmentVariable
func (_e *MockApplicationRepository_Expecter) UpdateEnvVar(ctx interface{}, env interface{}) *MockApplicationRepository_UpdateEnvVar_Call {
	return &MockApplicationRepository_UpdateEnvVar_Call{Call: _e.mock.On("UpdateEnvVar", ctx, env)}
}

func (_c *MockApplicationRepository_UpdateEnvVar_Call) Run(run func(ctx context.Context, env *domain.EnvironmentVariable)) *MockApplicationRepository_UpdateEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.EnvironmentVariable))
	})
	return _c
}

func (_c *MockApplicationRepository_UpdateEnvVar_Call) Return(_a0 error) *MockApplicationRepository_UpdateEnvVar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_UpdateEnvVar_Call) RunAndReturn(run func(context.Context, *domain.EnvironmentVariable) error) *MockApplicationRepository_UpdateEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHealth provides a mock function with given fields: ctx, serverID, reports
func (_m *MockApplicationRepository) UpdateHealth(ctx context.Context, serverID uuid.UUID, reports []domain.ApplicationHealth) error {
	ret := _m.Called(ctx, serverID, reports)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.ApplicationHealth) error); ok {
		r0 = rf(ctx, serverID, reports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_UpdateHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHealth'
type MockApplicationRepository_UpdateHealth_Call struct {
	*mock.Call
}

// UpdateHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - reports []domain.ApplicationHealth
func (_e *MockApplicationRepository_Expecter) UpdateHealth(ctx interface{}, serverID interface{}, reports interface{}) *MockApplicationRepository_UpdateHealth_Call {
	return &MockApplicationRepository_UpdateHealth_Call{Call: _e.mock.On("UpdateHealth", ctx, serverID, reports)}
}

func (_c *MockApplicationRepository_UpdateHealth_Call) Run(run func(ctx context.Context, serverID uuid.UUID, reports []domain.ApplicationHealth)) *MockApplicationRepository_UpdateHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]domain.ApplicationHealth))
	})
	return _c
}

func (_c *MockApplicationRepository_UpdateHealth_Call) Return(_a0 error) *MockApplicationRepository_UpdateHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_UpdateHealth_Call) RunAndReturn(run func(context.Context, uuid.UUID, []domain.ApplicationHealth) error) *MockApplicationRepository_UpdateHealth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastDeployment provides a mock function with given fields: ctx, appID
func (_m *MockApplicationRepository) UpdateLastDeployment(ctx context.Context, appID int64) error {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastDeployment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_UpdateLastDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastDeployment'
type MockApplicationRepository_UpdateLastDeployment_Call struct {
	*mock.Call
}

// UpdateLastDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockApplicationRepository_Expecter) UpdateLastDeployment(ctx interface{}, appID interface{}) *MockApplicationRepository_UpdateLastDeployment_Call {
	return &MockApplicationRepository_UpdateLastDeployment_Call{Call: _e.mock.On("UpdateLastDeployment", ctx, appID)}
}

func (_c *MockApplicationRepository_UpdateLastDeployment_Call) Run(run func(ctx context.Context, appID int64)) *MockApplicationRepository_UpdateLastDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApplicationRepository_UpdateLastDeployment_Call) Return(_a0 error) *MockApplicationRepository_UpdateLastDeployment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_UpdateLastDeployment_Call) RunAndReturn(run func(context.Context, int64) error) *MockApplicationRepository_UpdateLastDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, appID, status
func (_m *MockApplicationRepository) UpdateStatus(ctx context.Context, appID int64, status domain.ApplicationStatus) error {
	ret := _m.Called(ctx, appID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.ApplicationStatus) error); ok {
		r0 = rf(ctx, appID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplicationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockApplicationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
//   - status domain.ApplicationStatus
func (_e *MockApplicationRepository_Expecter) UpdateStatus(ctx interface{}, appID interface{}, status interface{}) *MockApplicationRepository_UpdateStatus_Call {
	return &MockApplicationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, appID, status)}
}

func (_c *MockApplicationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, appID int64, status domain.ApplicationStatus)) *MockApplicationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.ApplicationStatus))
	})
	return _c
}

func (_c *MockApplicationRepository_UpdateStatus_Call) Return(_a0 error) *MockApplicationRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplicationRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, domain.ApplicationStatus) error) *MockApplicationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplicationRepository creates a new instance of MockApplicationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationRepository {
	mock := &MockApplicationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
