// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// BulkInsert provides a mock function with given fields: ctx, metrics
func (_m *MockMetricsRepository) BulkInsert(ctx context.Context, metrics []domain.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsRepository_BulkInsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsert'
type MockMetricsRepository_BulkInsert_Call struct {
	*mock.Call
}

// BulkInsert is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []domain.Metrics
func (_e *MockMetricsRepository_Expecter) BulkInsert(ctx interface{}, metrics interface{}) *MockMetricsRepository_BulkInsert_Call {
	return &MockMetricsRepository_BulkInsert_Call{Call: _e.mock.On("BulkInsert", ctx, metrics)}
}

func (_c *MockMetricsRepository_BulkInsert_Call) Run(run func(ctx context.Context, metrics []domain.Metrics)) *MockMetricsRepository_BulkInsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Metrics))
	})
	return _c
}

func (_c *MockMetricsRepository_BulkInsert_Call) Return(_a0 error) *MockMetricsRepository_BulkInsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsRepository_BulkInsert_Call) RunAndReturn(run func(context.Context, []domain.Metrics) error) *MockMetricsRepository_BulkInsert_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields: ctx, serverID, cutoff
func (_m *MockMetricsRepository) Cleanup(ctx context.Context, serverID uuid.UUID, cutoff time.Time) error {
	ret := _m.Called(ctx, serverID, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, serverID, cutoff)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsRepository_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockMetricsRepository_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - cutoff time.Time
func (_e *MockMetricsRepository_Expecter) Cleanup(ctx interface{}, serverID interface{}, cutoff interface{}) *MockMetricsRepository_Cleanup_Call {
	return &MockMetricsRepository_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx, serverID, cutoff)}
}

func (_c *MockMetricsRepository_Cleanup_Call) Run(run func(ctx context.Context, serverID uuid.UUID, cutoff time.Time)) *MockMetricsRepository_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockMetricsRepository_Cleanup_Call) Return(_a0 error) *MockMetricsRepository_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsRepository_Cleanup_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockMetricsRepository_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
