// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockDeploymentRepository is an autogenerated mock type for the DeploymentRepository type
type MockDeploymentRepository struct {
	mock.Mock
}

type MockDeploymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentRepository) EXPECT() *MockDeploymentRepository_Expecter {
	return &MockDeploymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, deployment
func (_m *MockDeploymentRepository) Create(ctx context.Context, deployment *domain.Deployment) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deployment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deployment) (*domain.Deployment, error)); ok {
		return rf(ctx, deployment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deployment) *domain.Deployment); ok {
		r0 = rf(ctx, deployment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Deployment) error); ok {
		r1 = rf(ctx, deployment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeploymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *domain.Deployment
func (_e *MockDeploymentRepository_Expecter) Create(ctx interface{}, deployment interface{}) *MockDeploymentRepository_Create_Call {
	return &MockDeploymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, deployment)}
}

func (_c *MockDeploymentRepository_Create_Call) Run(run func(ctx context.Context, deployment *domain.Deployment)) *MockDeploymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Deployment))
	})
	return _c
}

func (_c *MockDeploymentRepository_Create_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Deployment) (*domain.Deployment, error)) *MockDeploymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function with given fields: ctx, deploymentID
func (_m *MockDeploymentRepository) Finish(ctx context.Context, deploymentID int64) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Deployment, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Deployment); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockDeploymentRepository_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
func (_e *MockDeploymentRepository_Expecter) Finish(ctx interface{}, deploymentID interface{}) *MockDeploymentRepository_Finish_Call {
	return &MockDeploymentRepository_Finish_Call{Call: _e.mock.On("Finish", ctx, deploymentID)}
}

func (_c *MockDeploymentRepository_Finish_Call) Run(run func(ctx context.Context, deploymentID int64)) *MockDeploymentRepository_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDeploymentRepository_Finish_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_Finish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_Finish_Call) RunAndReturn(run func(context.Context, int64) (*domain.Deployment, error)) *MockDeploymentRepository_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, deploymentID
func (_m *MockDeploymentRepository) GetByID(ctx context.Context, deploymentID int64) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Deployment, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Deployment); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeploymentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
func (_e *MockDeploymentRepository_Expecter) GetByID(ctx interface{}, deploymentID interface{}) *MockDeploymentRepository_GetByID_Call {
	return &MockDeploymentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, deploymentID)}
}

func (_c *MockDeploymentRepository_GetByID_Call) Run(run func(ctx context.Context, deploymentID int64)) *MockDeploymentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDeploymentRepository_GetByID_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Deployment, error)) *MockDeploymentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockDeploymentRepository) List(ctx context.Context, opts domain.DeploymentListOptions) ([]*domain.Deployment, int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Deployment
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeploymentListOptions) ([]*domain.Deployment, int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeploymentListOptions) []*domain.Deployment); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.DeploymentListOptions) int64); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.DeploymentListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeploymentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeploymentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.DeploymentListOptions
func (_e *MockDeploymentRepository_Expecter) List(ctx interface{}, opts interface{}) *MockDeploymentRepository_List_Call {
	return &MockDeploymentRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockDeploymentRepository_List_Call) Run(run func(ctx context.Context, opts domain.DeploymentListOptions)) *MockDeploymentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DeploymentListOptions))
	})
	return _c
}

func (_c *MockDeploymentRepository_List_Call) Return(_a0 []*domain.Deployment, _a1 int64, _a2 error) *MockDeploymentRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeploymentRepository_List_Call) RunAndReturn(run func(context.Context, domain.DeploymentListOptions) ([]*domain.Deployment, int64, error)) *MockDeploymentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, deploymentID
func (_m *MockDeploymentRepository) Start(ctx context.Context, deploymentID int64) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Deployment, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Deployment); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDeploymentRepository_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
func (_e *MockDeploymentRepository_Expecter) Start(ctx interface{}, deploymentID interface{}) *MockDeploymentRepository_Start_Call {
	return &MockDeploymentRepository_Start_Call{Call: _e.mock.On("Start", ctx, deploymentID)}
}

func (_c *MockDeploymentRepository_Start_Call) Run(run func(ctx context.Context, deploymentID int64)) *MockDeploymentRepository_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDeploymentRepository_Start_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_Start_Call) RunAndReturn(run func(context.Context, int64) (*domain.Deployment, error)) *MockDeploymentRepository_Start_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommitInfo provides a mock function with given fields: ctx, deploymentID, commitHash, commitMessage
func (_m *MockDeploymentRepository) UpdateCommitInfo(ctx context.Context, deploymentID int64, commitHash string, commitMessage string) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deploymentID, commitHash, commitMessage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommitInfo")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (*domain.Deployment, error)); ok {
		return rf(ctx, deploymentID, commitHash, commitMessage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) *domain.Deployment); ok {
		r0 = rf(ctx, deploymentID, commitHash, commitMessage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, deploymentID, commitHash, commitMessage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_UpdateCommitInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommitInfo'
type MockDeploymentRepository_UpdateCommitInfo_Call struct {
	*mock.Call
}

// UpdateCommitInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
//   - commitHash string
//   - commitMessage string
func (_e *MockDeploymentRepository_Expecter) UpdateCommitInfo(ctx interface{}, deploymentID interface{}, commitHash interface{}, commitMessage interface{}) *MockDeploymentRepository_UpdateCommitInfo_Call {
	return &MockDeploymentRepository_UpdateCommitInfo_Call{Call: _e.mock.On("UpdateCommitInfo", ctx, deploymentID, commitHash, commitMessage)}
}

func (_c *MockDeploymentRepository_UpdateCommitInfo_Call) Run(run func(ctx context.Context, deploymentID int64, commitHash string, commitMessage string)) *MockDeploymentRepository_UpdateCommitInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockDeploymentRepository_UpdateCommitInfo_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_UpdateCommitInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_UpdateCommitInfo_Call) RunAndReturn(run func(context.Context, int64, string, string) (*domain.Deployment, error)) *MockDeploymentRepository_UpdateCommitInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, deploymentID, status
func (_m *MockDeploymentRepository) UpdateStatus(ctx context.Context, deploymentID int64, status domain.DeploymentStatus) (*domain.Deployment, error) {
	ret := _m.Called(ctx, deploymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *domain.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.DeploymentStatus) (*domain.Deployment, error)); ok {
		return rf(ctx, deploymentID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.DeploymentStatus) *domain.Deployment); ok {
		r0 = rf(ctx, deploymentID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.DeploymentStatus) error); ok {
		r1 = rf(ctx, deploymentID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeploymentRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockDeploymentRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID int64
//   - status domain.DeploymentStatus
func (_e *MockDeploymentRepository_Expecter) UpdateStatus(ctx interface{}, deploymentID interface{}, status interface{}) *MockDeploymentRepository_UpdateStatus_Call {
	return &MockDeploymentRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, deploymentID, status)}
}

func (_c *MockDeploymentRepository_UpdateStatus_Call) Run(run func(ctx context.Context, deploymentID int64, status domain.DeploymentStatus)) *MockDeploymentRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.DeploymentStatus))
	})
	return _c
}

func (_c *MockDeploymentRepository_UpdateStatus_Call) Return(_a0 *domain.Deployment, _a1 error) *MockDeploymentRepository_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeploymentRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, domain.DeploymentStatus) (*domain.Deployment, error)) *MockDeploymentRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeploymentRepository creates a new instance of MockDeploymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentRepository {
	mock := &MockDeploymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
