// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// SyncPermissions provides a mock function with given fields: ctx, data
func (_m *MockRoleRepository) SyncPermissions(ctx context.Context, data map[domain.RoleConst]map[domain.PermissionConst]bool) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SyncPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[domain.RoleConst]map[domain.PermissionConst]bool) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_SyncPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPermissions'
type MockRoleRepository_SyncPermissions_Call struct {
	*mock.Call
}

// SyncPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[domain.RoleConst]map[domain.PermissionConst]bool
func (_e *MockRoleRepository_Expecter) SyncPermissions(ctx interface{}, data interface{}) *MockRoleRepository_SyncPermissions_Call {
	return &MockRoleRepository_SyncPermissions_Call{Call: _e.mock.On("SyncPermissions", ctx, data)}
}

func (_c *MockRoleRepository_SyncPermissions_Call) Run(run func(ctx context.Context, data map[domain.RoleConst]map[domain.PermissionConst]bool)) *MockRoleRepository_SyncPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[domain.RoleConst]map[domain.PermissionConst]bool))
	})
	return _c
}

func (_c *MockRoleRepository_SyncPermissions_Call) Return(_a0 error) *MockRoleRepository_SyncPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_SyncPermissions_Call) RunAndReturn(run func(context.Context, map[domain.RoleConst]map[domain.PermissionConst]bool) error) *MockRoleRepository_SyncPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
