// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, j
func (_m *MockJobRepository) Create(ctx context.Context, j *domain.Job) (*domain.Job, error) {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Job) (*domain.Job, error)); ok {
		return rf(ctx, j)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Job) *domain.Job); ok {
		r0 = rf(ctx, j)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Job) error); ok {
		r1 = rf(ctx, j)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - j *domain.Job
func (_e *MockJobRepository_Expecter) Create(ctx interface{}, j interface{}) *MockJobRepository_Create_Call {
	return &MockJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, j)}
}

func (_c *MockJobRepository_Create_Call) Run(run func(ctx context.Context, j *domain.Job)) *MockJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Job))
	})
	return _c
}

func (_c *MockJobRepository_Create_Call) Return(_a0 *domain.Job, _a1 error) *MockJobRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Job) (*domain.Job, error)) *MockJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, jobID
func (_m *MockJobRepository) Delete(ctx context.Context, jobID int64) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJobRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
func (_e *MockJobRepository_Expecter) Delete(ctx interface{}, jobID interface{}) *MockJobRepository_Delete_Call {
	return &MockJobRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, jobID)}
}

func (_c *MockJobRepository_Delete_Call) Run(run func(ctx context.Context, jobID int64)) *MockJobRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockJobRepository_Delete_Call) Return(_a0 error) *MockJobRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockJobRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, jobID
func (_m *MockJobRepository) GetByID(ctx context.Context, jobID int64) (*domain.Job, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Job, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Job); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockJobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
func (_e *MockJobRepository_Expecter) GetByID(ctx interface{}, jobID interface{}) *MockJobRepository_GetByID_Call {
	return &MockJobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, jobID)}
}

func (_c *MockJobRepository_GetByID_Call) Run(run func(ctx context.Context, jobID int64)) *MockJobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockJobRepository_GetByID_Call) Return(_a0 *domain.Job, _a1 error) *MockJobRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Job, error)) *MockJobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPending provides a mock function with given fields: ctx, serverID
func (_m *MockJobRepository) GetPending(ctx context.Context, serverID uuid.UUID) ([]*domain.Job, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPending")
	}

	var r0 []*domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Job, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Job); ok {
		r0 = rf(ctx, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPending'
type MockJobRepository_GetPending_Call struct {
	*mock.Call
}

// GetPending is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockJobRepository_Expecter) GetPending(ctx interface{}, serverID interface{}) *MockJobRepository_GetPending_Call {
	return &MockJobRepository_GetPending_Call{Call: _e.mock.On("GetPending", ctx, serverID)}
}

func (_c *MockJobRepository_GetPending_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockJobRepository_GetPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockJobRepository_GetPending_Call) Return(_a0 []*domain.Job, _a1 error) *MockJobRepository_GetPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetPending_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Job, error)) *MockJobRepository_GetPending_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockJobRepository) List(ctx context.Context, opts domain.JobListOptions) ([]*domain.Job, int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Job
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.JobListOptions) ([]*domain.Job, int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.JobListOptions) []*domain.Job); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.JobListOptions) int64); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.JobListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJobRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockJobRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.JobListOptions
func (_e *MockJobRepository_Expecter) List(ctx interface{}, opts interface{}) *MockJobRepository_List_Call {
	return &MockJobRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockJobRepository_List_Call) Run(run func(ctx context.Context, opts domain.JobListOptions)) *MockJobRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.JobListOptions))
	})
	return _c
}

func (_c *MockJobRepository_List_Call) Return(_a0 []*domain.Job, _a1 int64, _a2 error) *MockJobRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJobRepository_List_Call) RunAndReturn(run func(context.Context, domain.JobListOptions) ([]*domain.Job, int64, error)) *MockJobRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFinished provides a mock function with given fields: ctx, jobID, status
func (_m *MockJobRepository) MarkFinished(ctx context.Context, jobID int64, status domain.JobStatus) (*domain.Job, error) {
	ret := _m.Called(ctx, jobID, status)

	if len(ret) == 0 {
		panic("no return value specified for MarkFinished")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.JobStatus) (*domain.Job, error)); ok {
		return rf(ctx, jobID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.JobStatus) *domain.Job); ok {
		r0 = rf(ctx, jobID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.JobStatus) error); ok {
		r1 = rf(ctx, jobID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_MarkFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFinished'
type MockJobRepository_MarkFinished_Call struct {
	*mock.Call
}

// MarkFinished is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
//   - status domain.JobStatus
func (_e *MockJobRepository_Expecter) MarkFinished(ctx interface{}, jobID interface{}, status interface{}) *MockJobRepository_MarkFinished_Call {
	return &MockJobRepository_MarkFinished_Call{Call: _e.mock.On("MarkFinished", ctx, jobID, status)}
}

func (_c *MockJobRepository_MarkFinished_Call) Run(run func(ctx context.Context, jobID int64, status domain.JobStatus)) *MockJobRepository_MarkFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.JobStatus))
	})
	return _c
}

func (_c *MockJobRepository_MarkFinished_Call) Return(_a0 *domain.Job, _a1 error) *MockJobRepository_MarkFinished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_MarkFinished_Call) RunAndReturn(run func(context.Context, int64, domain.JobStatus) (*domain.Job, error)) *MockJobRepository_MarkFinished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRunning provides a mock function with given fields: ctx, jobID
func (_m *MockJobRepository) MarkRunning(ctx context.Context, jobID int64) (*domain.Job, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRunning")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Job, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Job); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_MarkRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRunning'
type MockJobRepository_MarkRunning_Call struct {
	*mock.Call
}

// MarkRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
func (_e *MockJobRepository_Expecter) MarkRunning(ctx interface{}, jobID interface{}) *MockJobRepository_MarkRunning_Call {
	return &MockJobRepository_MarkRunning_Call{Call: _e.mock.On("MarkRunning", ctx, jobID)}
}

func (_c *MockJobRepository_MarkRunning_Call) Run(run func(ctx context.Context, jobID int64)) *MockJobRepository_MarkRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockJobRepository_MarkRunning_Call) Return(_a0 *domain.Job, _a1 error) *MockJobRepository_MarkRunning_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_MarkRunning_Call) RunAndReturn(run func(context.Context, int64) (*domain.Job, error)) *MockJobRepository_MarkRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Retry provides a mock function with given fields: ctx, jobID, j
func (_m *MockJobRepository) Retry(ctx context.Context, jobID int64, j *domain.Job) (*domain.Job, error) {
	ret := _m.Called(ctx, jobID, j)

	if len(ret) == 0 {
		panic("no return value specified for Retry")
	}

	var r0 *domain.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Job) (*domain.Job, error)); ok {
		return rf(ctx, jobID, j)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Job) *domain.Job); ok {
		r0 = rf(ctx, jobID, j)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *domain.Job) error); ok {
		r1 = rf(ctx, jobID, j)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_Retry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retry'
type MockJobRepository_Retry_Call struct {
	*mock.Call
}

// Retry is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
//   - j *domain.Job
func (_e *MockJobRepository_Expecter) Retry(ctx interface{}, jobID interface{}, j interface{}) *MockJobRepository_Retry_Call {
	return &MockJobRepository_Retry_Call{Call: _e.mock.On("Retry", ctx, jobID, j)}
}

func (_c *MockJobRepository_Retry_Call) Run(run func(ctx context.Context, jobID int64, j *domain.Job)) *MockJobRepository_Retry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Job))
	})
	return _c
}

func (_c *MockJobRepository_Retry_Call) Return(_a0 *domain.Job, _a1 error) *MockJobRepository_Retry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_Retry_Call) RunAndReturn(run func(context.Context, int64, *domain.Job) (*domain.Job, error)) *MockJobRepository_Retry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
