// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockLogRepository is an autogenerated mock type for the LogRepository type
type MockLogRepository struct {
	mock.Mock
}

type MockLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogRepository) EXPECT() *MockLogRepository_Expecter {
	return &MockLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, l
func (_m *MockLogRepository) Create(ctx context.Context, l *domain.Log) (*domain.Log, error) {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Log) (*domain.Log, error)); ok {
		return rf(ctx, l)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Log) *domain.Log); ok {
		r0 = rf(ctx, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Log) error); ok {
		r1 = rf(ctx, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - l *domain.Log
func (_e *MockLogRepository_Expecter) Create(ctx interface{}, l interface{}) *MockLogRepository_Create_Call {
	return &MockLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, l)}
}

func (_c *MockLogRepository_Create_Call) Run(run func(ctx context.Context, l *domain.Log)) *MockLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Log))
	})
	return _c
}

func (_c *MockLogRepository_Create_Call) Return(_a0 *domain.Log, _a1 error) *MockLogRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Log) (*domain.Log, error)) *MockLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockLogRepository) List(ctx context.Context, opts domain.LogListOptions) ([]*domain.Log, int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Log
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogListOptions) ([]*domain.Log, int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogListOptions) []*domain.Log); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LogListOptions) int64); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.LogListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.LogListOptions
func (_e *MockLogRepository_Expecter) List(ctx interface{}, opts interface{}) *MockLogRepository_List_Call {
	return &MockLogRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockLogRepository_List_Call) Run(run func(ctx context.Context, opts domain.LogListOptions)) *MockLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LogListOptions))
	})
	return _c
}

func (_c *MockLogRepository_List_Call) Return(_a0 []*domain.Log, _a1 int64, _a2 error) *MockLogRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLogRepository_List_Call) RunAndReturn(run func(context.Context, domain.LogListOptions) ([]*domain.Log, int64, error)) *MockLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogRepository creates a new instance of MockLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogRepository {
	mock := &MockLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
