// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "horizonx/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockServerRepository is an autogenerated mock type for the ServerRepository type
type MockServerRepository struct {
	mock.Mock
}

type MockServerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerRepository) EXPECT() *MockServerRepository_Expecter {
	return &MockServerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockServerRepository) Create(ctx context.Context, s *domain.Server) (*domain.Server, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) (*domain.Server, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) *domain.Server); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Server) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *domain.Server
func (_e *MockServerRepository_Expecter) Create(ctx interface{}, s interface{}) *MockServerRepository_Create_Call {
	return &MockServerRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockServerRepository_Create_Call) Run(run func(ctx context.Context, s *domain.Server)) *MockServerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Server))
	})
	return _c
}

func (_c *MockServerRepository_Create_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Server) (*domain.Server, error)) *MockServerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, serverID
func (_m *MockServerRepository) Delete(ctx context.Context, serverID uuid.UUID) error {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockServerRepository_Expecter) Delete(ctx interface{}, serverID interface{}) *MockServerRepository_Delete_Call {
	return &MockServerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, serverID)}
}

func (_c *MockServerRepository_Delete_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockServerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockServerRepository_Delete_Call) Return(_a0 error) *MockServerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockServerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, serverID
func (_m *MockServerRepository) GetByID(ctx context.Context, serverID uuid.UUID) (*domain.Server, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Server, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Server); ok {
		r0 = rf(ctx, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockServerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockServerRepository_Expecter) GetByID(ctx interface{}, serverID interface{}) *MockServerRepository_GetByID_Call {
	return &MockServerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, serverID)}
}

func (_c *MockServerRepository_GetByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockServerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockServerRepository_GetByID_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Server, error)) *MockServerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *MockServerRepository) GetByToken(ctx context.Context, token string) (*domain.Server, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockServerRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockServerRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *MockServerRepository_GetByToken_Call {
	return &MockServerRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *MockServerRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *MockServerRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepository_GetByToken_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*domain.Server, error)) *MockServerRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockServerRepository) List(ctx context.Context, opts domain.ServerListOptions) ([]*domain.Server, int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Server
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ServerListOptions) ([]*domain.Server, int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ServerListOptions) []*domain.Server); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ServerListOptions) int64); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ServerListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServerRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServerRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.ServerListOptions
func (_e *MockServerRepository_Expecter) List(ctx interface{}, opts interface{}) *MockServerRepository_List_Call {
	return &MockServerRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockServerRepository_List_Call) Run(run func(ctx context.Context, opts domain.ServerListOptions)) *MockServerRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ServerListOptions))
	})
	return _c
}

func (_c *MockServerRepository_List_Call) Return(_a0 []*domain.Server, _a1 int64, _a2 error) *MockServerRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServerRepository_List_Call) RunAndReturn(run func(context.Context, domain.ServerListOptions) ([]*domain.Server, int64, error)) *MockServerRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s, serverID
func (_m *MockServerRepository) Update(ctx context.Context, s *domain.Server, serverID uuid.UUID) error {
	ret := _m.Called(ctx, s, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server, uuid.UUID) error); ok {
		r0 = rf(ctx, s, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s *domain.Server
//   - serverID uuid.UUID
func (_e *MockServerRepository_Expecter) Update(ctx interface{}, s interface{}, serverID interface{}) *MockServerRepository_Update_Call {
	return &MockServerRepository_Update_Call{Call: _e.mock.On("Update", ctx, s, serverID)}
}

func (_c *MockServerRepository_Update_Call) Run(run func(ctx context.Context, s *domain.Server, serverID uuid.UUID)) *MockServerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Server), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockServerRepository_Update_Call) Return(_a0 error) *MockServerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Server, uuid.UUID) error) *MockServerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOSInfo provides a mock function with given fields: ctx, serverID, osInfo
func (_m *MockServerRepository) UpdateOSInfo(ctx context.Context, serverID uuid.UUID, osInfo domain.OSInfo) error {
	ret := _m.Called(ctx, serverID, osInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOSInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.OSInfo) error); ok {
		r0 = rf(ctx, serverID, osInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_UpdateOSInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOSInfo'
type MockServerRepository_UpdateOSInfo_Call struct {
	*mock.Call
}

// UpdateOSInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - osInfo domain.OSInfo
func (_e *MockServerRepository_Expecter) UpdateOSInfo(ctx interface{}, serverID interface{}, osInfo interface{}) *MockServerRepository_UpdateOSInfo_Call {
	return &MockServerRepository_UpdateOSInfo_Call{Call: _e.mock.On("UpdateOSInfo", ctx, serverID, osInfo)}
}

func (_c *MockServerRepository_UpdateOSInfo_Call) Run(run func(ctx context.Context, serverID uuid.UUID, osInfo domain.OSInfo)) *MockServerRepository_UpdateOSInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.OSInfo))
	})
	return _c
}

func (_c *MockServerRepository_UpdateOSInfo_Call) Return(_a0 error) *MockServerRepository_UpdateOSInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_UpdateOSInfo_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.OSInfo) error) *MockServerRepository_UpdateOSInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, serverID, isOnline
func (_m *MockServerRepository) UpdateStatus(ctx context.Context, serverID uuid.UUID, isOnline bool) error {
	ret := _m.Called(ctx, serverID, isOnline)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, serverID, isOnline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockServerRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - isOnline bool
func (_e *MockServerRepository_Expecter) UpdateStatus(ctx interface{}, serverID interface{}, isOnline interface{}) *MockServerRepository_UpdateStatus_Call {
	return &MockServerRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, serverID, isOnline)}
}

func (_c *MockServerRepository_UpdateStatus_Call) Run(run func(ctx context.Context, serverID uuid.UUID, isOnline bool)) *MockServerRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockServerRepository_UpdateStatus_Call) Return(_a0 error) *MockServerRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockServerRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerRepository creates a new instance of MockServerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerRepository {
	mock := &MockServerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
