package app

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"

	"github.com/google/uuid"
)

// newBubbleEnv generates a fresh secret set for a bubble.
func newBubbleEnv(host string) (*bubbleEnv, error) {
	jwtSecret, err := randomHex(32)
	if err != nil {
		return nil, err
	}
	pgPass, err := randomHex(16)
	if err != nil {
		return nil, err
	}
	redisPass, err := randomHex(16)
	if err != nil {
		return nil, err
	}
	agentSecret, err := randomHex(32)
	if err != nil {
		return nil, err
	}
	if host == "" {
		host = "127.0.0.1"
	}
	return &bubbleEnv{
		HTTPAddr:         ":" + ServerPort,
		DashboardPort:    DashboardPort,
		JWTSecret:        jwtSecret,
		ServerID:         uuid.New().String(),
		AgentSecret:      agentSecret,
		PostgresPassword: pgPass,
		RedisPassword:    redisPass,
		Host:             host,
	}, nil
}

// renderBubbleEnv renders the bubble's .env. This is the single source of
// truth the server, dashboard, and agent all derive their URLs from.
func renderBubbleEnv(e *bubbleEnv) string {
	return fmt.Sprintf(`# HorizonX bubble — generated by `+"`horizonx install server`"+`
# Single source of truth: root .env interpolates into server/ + dashboard/.
APP_ENV=production
LOG_LEVEL=info
LOG_FORMAT=text
HTTP_ADDR=%s
TIME_ZONE=Asia/Jakarta

# JWT auth + env-var encryption key (AES-256-GCM derives from this).
JWT_SECRET=%s
JWT_EXPIRY=24h

# Postgres (compose service in the root compose).
POSTGRES_PASSWORD=%s
DATABASE_URL=postgres://postgres:%s@postgres:5432/horizonx?sslmode=disable

# Redis (compose service in the root compose).
REDIS_PASSWORD=%s
REDIS_ADDR=redis:6379

# Agent credentials — one token per app host. Install the agent there with:
#   HORIZONX_SERVER_ID=%s
#   HORIZONX_SERVER_API_TOKEN=%s
#   HORIZONX_API_URL=%s
#   HORIZONX_WS_URL=%s
HORIZONX_SERVER_ID=%s
HORIZONX_SERVER_API_TOKEN=%s
HORIZONX_API_URL=%s
HORIZONX_WS_URL=%s
AGENT_JOB_WORKER_COUNT=10

# Host-exposed ports (signature ports; override to change).
HORIZONX_PORT=%s
DASHBOARD_PORT=%s
`,
		e.HTTPAddr, e.JWTSecret,
		e.PostgresPassword, e.PostgresPassword,
		e.RedisPassword,
		e.ServerID, e.AgentSecret, ServerAPIURL(e.Host), ServerWSURL(e.Host),
		e.ServerID, e.AgentSecret, ServerAPIURL(e.Host), ServerWSURL(e.Host),
		ServerPort, e.DashboardPort,
	)
}

// randomHex returns n random bytes hex-encoded (2n chars).
func randomHex(bytes int) (string, error) {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
