package app

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/google/uuid"
)

// newBubbleEnv generates a fresh secret set for a bubble. adminEmail and
// adminPass become the first admin user (auto-seeded at server boot); empty
// adminPass generates a random one. allowedOrigins is the list of browser
// origins permitted to open the user WebSocket (gorilla CheckOrigin); when
// empty it defaults to the same-box dashboard origin so the WS works without
// extra config (see TK-0019 / the wss://…/api/ws/user connection-refused bug).
func newBubbleEnv(host, adminEmail, adminPass string, allowedOrigins []string) (*bubbleEnv, error) {
	jwtSecret, err := randomHex(32)
	if err != nil {
		return nil, err
	}
	pgPass, err := randomHex(16)
	if err != nil {
		return nil, err
	}
	redisPass, err := randomHex(16)
	if err != nil {
		return nil, err
	}
	agentSecret, err := randomHex(32)
	if err != nil {
		return nil, err
	}
	if host == "" {
		host = "127.0.0.1"
	}
	if adminEmail == "" {
		adminEmail = "admin@horizonx.local"
	}
	if adminPass == "" {
		adminPass, err = randomPassword()
		if err != nil {
			return nil, err
		}
	}
	// Default the WS allowed origins to the same-box dashboard URL. The
	// browser opens the dashboard at http://<host>:<dashboardPort> and the
	// WS carries that as its Origin; without it in ALLOWED_ORIGINS the
	// gorilla upgrader rejects the handshake (CONNECTION_REFUSED in the
	// browser). Tunnel/domain users pass --origin to add their public URL.
	if len(allowedOrigins) == 0 {
		allowedOrigins = []string{"http://" + host + ":" + DashboardPort}
	}
	// Internal convention: the server listens on :3000 INSIDE the bubble
	// (matches the dashboard's nginx upstream `server:3000` and the compose
	// port mapping 4858->3000). The signature port 4858 is what's exposed on
	// the host interface via HORIZONX_PORT.
	return &bubbleEnv{
		HTTPAddr:         ":3000",
		DashboardPort:    DashboardPort,
		JWTSecret:        jwtSecret,
		ServerID:         uuid.New().String(),
		AgentSecret:      agentSecret,
		PostgresPassword: pgPass,
		RedisPassword:    redisPass,
		Host:             host,
		AdminEmail:       adminEmail,
		AdminPass:        adminPass,
		AllowedOrigins:   allowedOrigins,
	}, nil
}

// randomPassword generates a strong-ish 20-char password from crypto/rand
// (upper + lower + digits + a few symbols — no ambiguous chars).
func randomPassword() (string, error) {
	const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*-_=+"
	b := make([]byte, 20)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	for i := range b {
		b[i] = alphabet[int(b[i])%len(alphabet)]
	}
	return string(b), nil
}

// renderBubbleEnv renders the bubble's .env. This is the single source of
// truth the server, dashboard, and agent all derive their URLs from.
func renderBubbleEnv(e *bubbleEnv) string {
	return fmt.Sprintf(`# HorizonX bubble — generated by `+"`horizonx install server`"+`
# Single source of truth: root .env interpolates into server/ + dashboard/.
APP_ENV=production
LOG_LEVEL=info
LOG_FORMAT=text
HTTP_ADDR=%s
TIME_ZONE=Asia/Jakarta

# JWT auth + env-var encryption key (AES-256-GCM derives from this).
JWT_SECRET=%s
JWT_EXPIRY=24h

# Postgres (compose service in the root compose).
POSTGRES_PASSWORD=%s
DATABASE_URL=postgres://postgres:%s@postgres:5432/horizonx?sslmode=disable

# Redis (compose service in the root compose).
REDIS_PASSWORD=%s
REDIS_PASS=%s
REDIS_ADDR=redis:6379

# Agent credentials — one token per app host. Install the agent there with:
#   HORIZONX_SERVER_ID=%s
#   HORIZONX_SERVER_API_TOKEN=%s
#   HORIZONX_API_URL=%s
#   HORIZONX_WS_URL=%s
HORIZONX_SERVER_ID=%s
HORIZONX_SERVER_API_TOKEN=%s
HORIZONX_API_URL=%s
HORIZONX_WS_URL=%s
AGENT_JOB_WORKER_COUNT=10

# Host-exposed ports (signature ports; override to change).
HORIZONX_PORT=%s
DASHBOARD_PORT=%s

# Browser origins allowed to open the user WebSocket (gorilla CheckOrigin).
# Defaults to the same-box dashboard URL so the WS works without extra config;
# add your public/tunnel domain here if you access the dashboard remotely
# (comma-separated). See TK-0019.
ALLOWED_ORIGINS=%s

# First admin user — auto-seeded by the server on first boot (AUTO_SEED).
# Shown once at the end of: horizonx install server
ADMIN_EMAIL=%s
ADMIN_PASSWORD=%s
AUTO_SEED=true
`,
		e.HTTPAddr, e.JWTSecret,
		e.PostgresPassword, e.PostgresPassword,
		e.RedisPassword, e.RedisPassword,
		e.ServerID, e.AgentSecret, ServerAPIURL(e.Host), ServerWSURL(e.Host),
		e.ServerID, e.AgentSecret, ServerAPIURL(e.Host), ServerWSURL(e.Host),
		ServerPort, e.DashboardPort,
		strings.Join(e.AllowedOrigins, ","),
		e.AdminEmail, e.AdminPass,
	)
}

// randomHex returns n random bytes hex-encoded (2n chars).
func randomHex(bytes int) (string, error) {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
