package app

// `horizonx install agent` — install OR upgrade the HorizonX agent on this host.
//
// The agent NEVER runs in docker (design rule locked with Maul, 2026-08-03):
// its job is to run docker-compose deploys on the host, read host hardware
// (/sys, hwmon, powercap, nvidia-smi), and survive `docker compose down` to
// redeploy the bubble. So provisioning creates a dedicated system user with
// docker group membership, a git SSH key, hwmon udev rules, an env file, and
// a systemd unit — no container involved.
//
// When run on the same box as the server, it reads the agent credentials
// (server ID + token + API/WS URLs) from the bubble's .env at /opt/horizonx.
// On a different host, pass --server/--token.

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// InstallAgentOptions carries the flags for `horizonx install agent`.
type InstallAgentOptions struct {
	Server string // control-plane base URL (http://host:4858); default: read from bubble .env
	Token  string // agent token; default: read from bubble .env
	Yes    bool
}

// RunInstallAgent provisions (or re-provisions, i.e. upgrades) the agent.
func RunInstallAgent(opts InstallAgentOptions) error {
	prov := defaultAgentProvision()

	if opts.Server == "" || opts.Token == "" {
		if err := loadAgentCredsFromBubble(prov); err != nil {
			return err
		}
	} else {
		prov.APIURL = strings.TrimRight(opts.Server, "/")
		prov.WSURL = strings.Replace(prov.APIURL, "http://", "ws://", 1) + "/ws/agent"
		// Token is passed whole as HORIZONX_SERVER_API_TOKEN; ServerID is
		// embedded in the token ("<uuid>.<secret>") when generated by the
		// bubble — split on the first dot for the server ID.
		if i := strings.Index(opts.Token, "."); i > 0 {
			prov.ServerID = opts.Token[:i]
			prov.ServerToken = opts.Token[i+1:]
		} else {
			prov.ServerToken = opts.Token
		}
	}

	fmt.Println("horizonx install agent — host systemd agent")
	fmt.Println()
	fmt.Printf("  server    : %s\n", prov.APIURL)
	fmt.Printf("  user      : %s\n", prov.UserName)
	fmt.Printf("  data dir  : %s\n", prov.DataDir)
	fmt.Println()

	if err := ProvisionAgent(prov); err != nil {
		return fmt.Errorf("provision agent: %w", err)
	}

	fmt.Println()
	fmt.Println("✔ Agent provisioned and started.")
	fmt.Println("  SSH key (add to GitHub for git deploys):")
	key := filepath.Join(prov.DataDir, ".ssh", "id_ed25519.pub")
	if data, err := os.ReadFile(key); err == nil {
		fmt.Println("    " + strings.TrimSpace(string(data)))
	} else {
		fmt.Printf("    (see %s)\n", key)
	}
	return nil
}

// loadAgentCredsFromBubble reads agent credentials from the server bubble's
// .env at /opt/horizonx (same-box install). Errors explain where to get them.
func loadAgentCredsFromBubble(prov *AgentProvision) error {
	envPath := filepath.Join(bubbleDir, ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		return fmt.Errorf("no --server/--token given and no server bubble found at %s.\n"+
			"  On the same box as the server, install the server first (horizonx install server).\n"+
			"  On a different host, pass: horizonx install agent --server http://host:4858 --token <token>", envPath)
	}
	vars := parseEnv(string(data))
	prov.ServerID = vars["HORIZONX_SERVER_ID"]
	prov.ServerToken = vars["HORIZONX_SERVER_API_TOKEN"]
	prov.APIURL = vars["HORIZONX_API_URL"]
	prov.WSURL = vars["HORIZONX_WS_URL"]
	if prov.APIURL == "" || prov.ServerToken == "" {
		return fmt.Errorf("server bubble .env at %s is missing agent credentials (HORIZONX_API_URL / HORIZONX_SERVER_API_TOKEN).\n"+
			"  Re-run: horizonx install server --generate-only", envPath)
	}
	return nil
}

// parseEnv parses KEY=VALUE lines (ignores comments/blank). Used to read the
// bubble .env for agent credentials.
func parseEnv(content string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if i := strings.Index(line, "="); i > 0 {
			out[strings.TrimSpace(line[:i])] = strings.TrimSpace(line[i+1:])
		}
	}
	return out
}

// InstallAgentFlags parses `horizonx install agent` flags.
func InstallAgentFlags(args []string) (InstallAgentOptions, error) {
	fs := flag.NewFlagSet("install agent", flag.ExitOnError)
	var opts InstallAgentOptions
	fs.StringVar(&opts.Server, "server", "", "control-plane base URL (http://host:4858); default: read from bubble .env")
	fs.StringVar(&opts.Token, "token", "", "agent token; default: read from bubble .env")
	fs.BoolVar(&opts.Yes, "yes", false, "non-interactive")
	if err := fs.Parse(args); err != nil {
		return opts, err
	}
	return opts, nil
}
