package app

import (
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/uuid"
)

// RunSetup bootstraps a HorizonX control plane: it generates secrets,
// writes .env, emits a self-contained docker-compose.yml (postgres + redis +
// server + dashboard) and prints systemd unit templates.
//
// Non-interactive by default — flags/env override everything, so it works in
// scripts and CI as well as on a fresh box.
//
// Usage:
//
//	horizonx setup                 # defaults into ./horizonx-setup
//	horizonx setup --dir /opt/horizonx --host 203.0.113.10
func RunSetup() error {
	fs := flag.NewFlagSet("setup", flag.ExitOnError)
	dir := fs.String("dir", "horizonx-setup", "output directory for generated files")
	host := fs.String("host", "127.0.0.1", "public IP/FQDN agents and the dashboard will use to reach the server")
	httpAddr := fs.String("http-addr", ":3000", "server listen address")
	serverTag := fs.String("server-tag", "latest", "horizonx server image tag")
	dashboardTag := fs.String("dashboard-tag", "latest", "horizonx dashboard image tag")
	agentVersion := fs.String("agent-version", "latest", "horizonx-agent binary version to install on app hosts")
	if err := fs.Parse(os.Args[2:]); err != nil {
		return err
	}

	outDir, err := filepath.Abs(*dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// --- Generate secrets -------------------------------------------------
	jwtSecret, err := randomHex(32)
	if err != nil {
		return err
	}
	serverID := uuid.New()
	agentSecret, err := randomHex(32)
	if err != nil {
		return err
	}
	agentToken := fmt.Sprintf("%s.%s", serverID.String(), agentSecret)

	envPath := filepath.Join(outDir, ".env")
	env := fmt.Sprintf(`# HorizonX control plane — generated by `+"`horizonx setup`"+`
# Production requires a strong JWT_SECRET (the server refuses dev defaults).
APP_ENV=production
LOG_LEVEL=info
LOG_FORMAT=text
HTTP_ADDR=%s
TIME_ZONE=Asia/Jakarta

# JWT auth + env-var encryption key (AES-256-GCM derives from this).
JWT_SECRET=%s
JWT_EXPIRY=24h

# Postgres (compose service below).
DATABASE_URL=postgres://postgres:change-me@postgres:5432/horizonx?sslmode=disable

# Redis (compose service below).
REDIS_ADDR=redis:6379
REDIS_PASS=

# Agent credentials — one token per app host. Install the agent there with:
#   HORIZONX_SERVER_ID=%s
#   HORIZONX_SERVER_API_TOKEN=%s
#   HORIZONX_API_URL=http://%s:3000
#   HORIZONX_WS_URL=ws://%s:3000/ws/agent
HORIZONX_SERVER_ID=%s
HORIZONX_SERVER_API_TOKEN=%s
HORIZONX_API_URL=http://%s:3000
HORIZONX_WS_URL=ws://%s:3000/ws/agent
AGENT_JOB_WORKER_COUNT=10

# Optional: Discord-style webhook notified on deploy success/failure.
# WEBHOOK_URL=https://discord.com/api/webhooks/...
`, *httpAddr, jwtSecret, serverID.String(), agentSecret, *host, *host, serverID.String(), agentSecret, *host, *host)

	if err := os.WriteFile(envPath, []byte(env), 0o600); err != nil {
		return fmt.Errorf("write .env: %w", err)
	}

	// --- Emit docker-compose.yml ------------------------------------------
	composePath := filepath.Join(outDir, "docker-compose.yml")
	compose := fmt.Sprintf(`# HorizonX control plane — generated by `+"`horizonx setup`"+`
# Bring up the stack with:
#   docker compose up -d
# Then open http://<host>:8080 for the dashboard (first login: admin@horizonx.local / <generated>).
# NOTE: the dashboard container serves the SPA; the server binary (horizonx server)
# exposes the API + /metrics.

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: horizonx
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [horizonx]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    networks: [horizonx]
    restart: unless-stopped

  server:
    image: ghcr.io/zlnew/horizonx:%s
    env_file: .env
    ports:
      - "%s:3000"
    depends_on:
      - postgres
      - redis
    networks: [horizonx]
    restart: unless-stopped

  dashboard:
    image: ghcr.io/zlnew/horizonx-dashboard:%s
    environment:
      VITE_API_URL: http://server:3000
    ports:
      - "8080:80"
    depends_on:
      - server
    networks: [horizonx]
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:

networks:
  horizonx:
    driver: bridge
`, *serverTag, *httpAddr, *dashboardTag)
	if err := os.WriteFile(composePath, []byte(compose), 0o644); err != nil {
		return fmt.Errorf("write compose: %w", err)
	}

	// --- Emit systemd units ------------------------------------------------
	sysDir := filepath.Join(outDir, "systemd")
	if err := os.MkdirAll(sysDir, 0o755); err != nil {
		return err
	}
	for _, unit := range []string{"horizonx-server.service", "horizonx-agent.service"} {
		data, err := systemdUnit(unit)
		if err != nil {
			return fmt.Errorf("embed %s: %w", unit, err)
		}
		if err := os.WriteFile(filepath.Join(sysDir, unit), data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", unit, err)
		}
	}

	// --- Print next steps -------------------------------------------------
	fmt.Println("✔ HorizonX control-plane setup complete.")
	fmt.Println()
	fmt.Println("  Output dir :", outDir)
	fmt.Println("  Agent token: " + agentToken)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  1. cd %s\n", outDir)
	fmt.Println("  2. docker compose up -d          # postgres + redis + server + dashboard")
	fmt.Println("  3. Open http://<host>:8080       # dashboard (admin@horizonx.local)")
	fmt.Println("  4. Install the agent on app hosts:")
	fmt.Println("       curl -fsSL https://raw.githubusercontent.com/zlnew/horizonx/main/install.sh | bash")
	fmt.Printf("       HORIZONX_SERVER_ID=%s HORIZONX_SERVER_API_TOKEN=%s HORIZONX_API_URL=http://%s:3000 HORIZONX_WS_URL=ws://%s:3000/ws/agent horizonx agent\n",
		serverID.String(), agentSecret, *host, *host)
	fmt.Println()
	fmt.Println("  Systemd units (bare-metal hosts instead of compose):")
	fmt.Printf("    sudo cp %s/systemd/*.service /etc/systemd/system/\n", outDir)
	fmt.Println("    sudo systemctl daemon-reload && sudo systemctl enable --now horizonx-server")
	fmt.Println()
	fmt.Println("Run `horizonx setup --help` to see overrides.")

	_ = agentVersion // reserved: will pin the agent install command per release
	return nil
}

func randomHex(bytes int) (string, error) {
	buf := make([]byte, bytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("crypto/rand: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
