// Package config
package config

import (
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/joho/godotenv"
)

type Config struct {
	AppEnv string

	LogLevel  string
	LogFormat string

	TimeZone       *time.Location
	Address        string
	AllowedOrigins []string
	DatabaseURL    string
	JWTSecret      string
	JWTExpiry      time.Duration

	AgentTargetAPIURL   string
	AgentTargetWsURL    string
	AgentServerAPIToken string
	AgentServerID       uuid.UUID
	AgentJobWorkerCount int

	// P2-15: optional webhook notified on deployment events.
	// Discord-style: POSTed a JSON payload with a text content field.
	WebhookURL string

	// AutoMigrate runs pending DB migrations at server boot (Laravel-style).
	// Controlled by AUTO_MIGRATE, default true.
	AutoMigrate bool

	// AutoSeed creates the admin user at server boot when the users table is
	// empty (controlled by AUTO_SEED, default true). Credentials come from
	// ADMIN_EMAIL / ADMIN_PASSWORD (defaults admin@horizonx.local + random
	// generated by `install server` into the instance .env).
	AutoSeed   bool
	AdminEmail string
	AdminPass  string

	RedisAddress  string
	RedisUsername string
	RedisPassword string
	RedisDB       int

	// TrustProxy makes login rate limiting + session IP capture key on the
	// FIRST X-Forwarded-For entry instead of the tunnel's RemoteAddr. Set
	// true when the server sits behind a trusted proxy (Cloudflare tunnel /
	// tailscale serve — the default HorizonX topology). Leave false when the
	// box is directly exposed, where a spoofed XFF must not bypass the
	// limiter.
	TrustProxy bool

	// DemoMode locks down destructive administrative actions (e.g. password
	// changes, server deletion, user management, application deletion)
	// for public sandbox demo instances.
	DemoMode bool
}

func Load() *Config {
	_ = godotenv.Load()

	appEnv := getEnv("APP_ENV", "local")

	// Logs
	logLevel := getEnv("LOG_LEVEL", "info")
	logFormat := getEnv("LOG_FORMAT", "text")

	// Server Time Zone
	timeZone, err := time.LoadLocation(getEnv("TIME_ZONE", "Local"))
	if err != nil {
		timeZone = time.Local
	}

	// Server HTTP Address
	addr := getEnv("HTTP_ADDR", ":3000")

	// Server Allowed Origins
	var origins []string
	rawOrigins := os.Getenv("ALLOWED_ORIGINS")
	if rawOrigins != "" {
		parts := strings.SplitSeq(rawOrigins, ",")
		for o := range parts {
			if trimmed := strings.TrimSpace(o); trimmed != "" {
				origins = append(origins, trimmed)
			}
		}
	}

	// Database URL
	databaseURL := getEnv("DATABASE_URL", "postgres://user:pass@localhost:5432/horizonx")

	// JWT Secret and Expiry
	jwtSecret := getEnv("JWT_SECRET", "")
	jwtExpiry := 24 * time.Hour
	if raw := os.Getenv("JWT_EXPIRY"); raw != "" {
		if duration, err := time.ParseDuration(raw); err == nil && duration > 0 {
			jwtExpiry = duration
		}
	}

	// AGENT Target URL
	agentTargetAPIURL := getEnv("HORIZONX_API_URL", "http://localhost:3000")
	agentTargetWsURL := getEnv("HORIZONX_WS_URL", "ws://localhost:3000/ws/agent")

	// AGENT Server Credentials
	agentServerAPIToken := getEnv("HORIZONX_SERVER_API_TOKEN", "")
	var agentServerID uuid.UUID
	if raw := os.Getenv("HORIZONX_SERVER_ID"); raw != "" {
		if serverID, err := uuid.Parse(raw); err == nil {
			agentServerID = serverID
		}
	}

	agentJobWorkerCount := 10
	if raw := os.Getenv("AGENT_JOB_WORKER_COUNT"); raw != "" {
		if count, err := strconv.Atoi(raw); err == nil {
			agentJobWorkerCount = count
		}
	}

	// P2-15: optional webhook (e.g. Discord) notified on deploy events.
	webhookURL := getEnv("WEBHOOK_URL", "")

	// Auto-migrate at boot unless explicitly disabled.
	autoMigrate := true
	if raw := strings.ToLower(os.Getenv("AUTO_MIGRATE")); raw != "" {
		autoMigrate = raw == "1" || raw == "true" || raw == "yes"
	}

	// Auto-seed the admin user at boot when the users table is empty.
	autoSeed := true
	if raw := strings.ToLower(os.Getenv("AUTO_SEED")); raw != "" {
		autoSeed = raw == "1" || raw == "true" || raw == "yes"
	}
	adminEmail := getEnv("ADMIN_EMAIL", "admin@horizonx.local")
	adminPass := getEnv("ADMIN_PASSWORD", "")

	// REDIS
	redisAddress := getEnv("REDIS_ADDR", "localhost:6379")
	redisUsername := getEnv("REDIS_USERNAME", "")
	redisPassword := getEnv("REDIS_PASS", "")
	redisDB := 0
	if raw := os.Getenv("REDIS_DB"); raw != "" {
		if value, err := strconv.Atoi(raw); err == nil {
			redisDB = value
		}
	}

	// TRUST_PROXY: default ON for the HorizonX topology (server binds
	// 127.0.0.1, exposed via Cloudflare tunnel / tailscale serve which set
	// X-Forwarded-For). Explicitly set TRUST_PROXY=false for direct exposure.
	trustProxy := true
	if raw := strings.ToLower(os.Getenv("TRUST_PROXY")); raw != "" {
		trustProxy = raw == "1" || raw == "true" || raw == "yes"
	}

	// DEMO_MODE: locks down destructive mutations for public sandbox demo.
	demoMode := false
	if raw := strings.ToLower(os.Getenv("DEMO_MODE")); raw != "" {
		demoMode = raw == "1" || raw == "true" || raw == "yes"
	}

	return &Config{
		AppEnv: appEnv,

		LogLevel:  logLevel,
		LogFormat: logFormat,

		TimeZone:       timeZone,
		Address:        addr,
		AllowedOrigins: origins,
		DatabaseURL:    databaseURL,
		JWTSecret:      jwtSecret,
		JWTExpiry:      jwtExpiry,

		AgentTargetAPIURL:   agentTargetAPIURL,
		AgentTargetWsURL:    agentTargetWsURL,
		AgentServerAPIToken: agentServerAPIToken,
		AgentServerID:       agentServerID,
		AgentJobWorkerCount: agentJobWorkerCount,

		WebhookURL: webhookURL,

		AutoMigrate: autoMigrate,

		AutoSeed:   autoSeed,
		AdminEmail: adminEmail,
		AdminPass:  adminPass,

		RedisAddress:  redisAddress,
		RedisUsername: redisUsername,
		RedisPassword: redisPassword,
		RedisDB:       redisDB,
		TrustProxy:    trustProxy,
		DemoMode:      demoMode,
	}
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
